/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.UserSession;
import config.config;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import main.login;

/**
 *
 * @author jhond
 */
public class editprofile extends javax.swing.JFrame {

    /**
     * Creates new form editprofile
     */
    private String path = "";

    public editprofile() {
        if (UserSession.getU_id() == 0) {
            JOptionPane.showMessageDialog(null, "Access Denied! Please Login First.");

            login login = new login();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
            return;
        }

        initComponents();
        this.setLocationRelativeTo(null);

        jTextField2.setText(UserSession.getInstance().getU_name());
        jTextField3.setText(UserSession.getInstance().getU_email());

        String existingPath = UserSession.getInstance().getImagePath();
        if (existingPath != null && !existingPath.isEmpty()) {
            config con = new config();
            con.setProfileIcon(Pic, existingPath);
            this.path = existingPath;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        Pic = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        email2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("EDIT PROFILE");
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 380, 50));

        Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/profile.png"))); // NOI18N
        Pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 62, 80), 3));
        jPanel2.add(Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 100, 100));

        jButton1.setBackground(new java.awt.Color(44, 62, 80));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SELECT IMAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 120, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 130, 30));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 170, 30));

        email2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email2.setForeground(new java.awt.Color(44, 62, 80));
        email2.setText("EMAIL:");
        jPanel2.add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        name2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name2.setForeground(new java.awt.Color(44, 62, 80));
        name2.setText("NAME:");
        jPanel2.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 40, -1));

        jToggleButton1.setBackground(new java.awt.Color(44, 62, 80));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("CONFIRM");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();

            try {
                BufferedImage original = ImageIO.read(f);

                BufferedImage resized = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);

                Graphics2D g2d = resized.createGraphics();
                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                g2d.drawImage(original, 0, 0, 100, 100, null);
                g2d.dispose();

                File dir = new File("src/pic");
                if (!dir.exists()) {
                    dir.mkdirs();
                }

                String fileName = "profile_" + System.currentTimeMillis() + ".png";
                File savedFile = new File(dir, fileName);

                ImageIO.write(resized, "png", savedFile);

                path = "src/pic/" + fileName;

                Pic.setIcon(new ImageIcon(resized));

                System.out.println("Image saved successfully to: " + path);

            } catch (IOException ex) {
                Logger.getLogger(editprofile.class
                        .getName()).log(Level.SEVERE, "Error saving profile image", ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked

    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        UserSession sess = UserSession.getInstance(); 
        config conf = new config();
        int userId = sess.getU_id();

        String name = jTextField2.getText().trim();
        if (name.isEmpty()) {
            name = sess.getU_name();
        }

        String finalPath = (this.path == null || this.path.isEmpty())
                ? sess.getImagePath()
                : this.path; //

        int confirm = JOptionPane.showConfirmDialog(null,
                "Apply changes to your profile, " + sess.getU_name() + "?",
                "Update Profile",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String sql = "UPDATE account SET username = ?, image = ? WHERE id = ?";
                conf.updateRecord(sql, name, finalPath, userId); 
                sess.setU_name(name);
                sess.setImagePath(finalPath); 

                JOptionPane.showMessageDialog(null, "Profile successfully updated!");

                this.dispose();
                if (sess.getU_type().equalsIgnoreCase("Admin")) {
                    new admin.DashBAdmin().setVisible(true);
                } else {
                    new customer.DashBUAcount().setVisible(true);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Update Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pic;
    private javax.swing.JLabel email2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
